" Generated from versions/coc-extensions; do not edit by hand.
let g:coc_global_extensions = [
            \ 'coc-clang-format-style-options@0.0.5',
            \ 'coc-clangd@0.33.0',
            \ 'coc-cmake@0.2.2',
            \ 'coc-css@2.2.2',
            \ 'coc-docker@1.0.2',
            \ 'coc-flutter@1.9.10',
            \ 'coc-go@1.3.35',
            \ 'coc-graphql@0.0.1',
            \ 'coc-highlight@2.0.5',
            \ 'coc-html@1.9.0',
            \ 'coc-json@1.9.12',
            \ 'coc-markdownlint@1.41.0',
            \ 'coc-python@1.2.13',
            \ 'coc-rust-analyzer@0.89.2',
            \ 'coc-sh@1.2.4',
            \ 'coc-snippets@3.4.10',
            \ 'coc-sql@0.15.0',
            \ 'coc-swagger@0.0.4',
            \ 'coc-toml@2.1.0',
            \ 'coc-vimlsp@0.13.1',
            \ 'coc-yaml@1.9.3',
            \ 'coc-yank@1.2.5',
            \ ]
